### ISSUE TITLE
proper credit Lívia

### ISSUE THREAD

**Issue by fczuardi** [onibushacker/site2017-2018#17]
a página de sobre é provisória, sim, mas me deparei aqui com a seguinte referencia https://github.com/onibushacker/hino/issues/1

entao se o draft for seguir e chegar na pagina mais madura, eu gostaria de trocar Evelyn por Capi na citação.

**Comment by barraponto** [comment]
@Eu registrei, mas frase foi proferida pela @liascava durante um evento da Unisul, em Florianópolis/SC, durante nossa longa jornada para o Abrelatam Uruguay em junho de 2013.
 
Era a resposta para a proposta "Defina o Ônibus Hacker em cinco palavras".

**Comment by fczuardi** [comment]
reopening to credit Livia instead
